### PR TITLE
Photo of Richard G. Stearns, USDJ

### PR DESCRIPTION
**Pull request by johnhawkinson**
speaking at the opening of Cambridge's Alewife Wetland, which resulted
  from the Boston Harbor cleanup litigation that he supervised under the
  Clean Water Act since 2004.

### CODE REVIEW

**Comment by mlissner** [comment]
I'm sure you realize we're sorting through the quality standards, but I think this one might be a good example of something that's not quite good enough. We're really looking for portraits, not wide shots like this one. I'll try to make this more clear. 

Do you have a closer shot?

**Comment by johnhawkinson** [comment]
Yeah, here's a narrower one, 1e6a8970a76b0e2246df5ff117ed6947cd7a26e5.
For some reason, I seemed to recall some goofy rule about including the flags on government portraits, but looking at the other images here, none of them are like that (though some have a flag background), so I don't know what I was thinking.

**Comment by mlissner** [comment]
A rule that requires flags in gov't portraits? That'd indeed be goofy. But, hey, I'm prepared to buy it.

Anyway, I just wanted to let you know that we're working on a process for getting photos like these integrated so that we don't have to be concerned about (the very serious) copyright issues that could come up.

**Comment by johnhawkinson** [comment]
It was more like a Guideline of some sort, not like a Federal Rule of Flag Procedure approved by the Judicial Conference and submitted to Congress on a you-must-vote-this-down-if-you-don't-like-it basis.
Anecdotally, of course.

**Pull request closed without merging**
